--------------------------------------------------------
--  File created - Friday-July-15-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAM_API_AUDIT
--------------------------------------------------------

  CREATE TABLE "IDANEUPCQ01"."CAM_API_AUDIT" 
   (	"AUDIT_ID" VARCHAR2(22 BYTE), 
	"RESOURCE_TYPE" VARCHAR2(10 BYTE), 
	"REQUEST_URI" VARCHAR2(100 BYTE), 
	"REQUEST_DATE" TIMESTAMP (6), 
	"DATA" CLOB, 
	"RESPONSE_STATUS" NUMBER(3,0), 
	"STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  Constraints for Table CAM_API_AUDIT
--------------------------------------------------------

  ALTER TABLE "IDANEUPCQ01"."CAM_API_AUDIT" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
  ALTER TABLE "IDANEUPCQ01"."CAM_API_AUDIT" MODIFY ("RESOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "IDANEUPCQ01"."CAM_API_AUDIT" MODIFY ("REQUEST_URI" NOT NULL ENABLE);
  ALTER TABLE "IDANEUPCQ01"."CAM_API_AUDIT" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "IDANEUPCQ01"."CAM_API_AUDIT" MODIFY ("RESPONSE_STATUS" NOT NULL ENABLE);
